[tool.poetry]
name = "my_note"
version = "0.1.0"
description = "Note for console"
authors = ["Aleksey Semenov <7.on.off@bk.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
